---
title: plynty website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  authors:
    title: authors
    output: true
  blogs:
    title: blogs
    output: true
  formats:
    title: formats
    output: true
  products:
    title: products
    output: true
  sections:
    title: sections
    output: true
  support-articles:
    title: support articles
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    format: ''
    page: ''
    image: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/post/:title.html"
    asset: ''
    image: ''
    author: ''
- scope:
    path: ''
    type: resetpassword
  values:
    layout: resetpassword
    permalink: "/resetpassword"
    asset: ''
    image: ''
    author: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
email: pfischer@vizuri.com
markdown: kramdown
excerpt_separator: "<!--more-->"
gems:
- jekyll-textile-converter
