---
title: plynty
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    description: Post descriptions
    image: https://plynty.com/uploads/plynty_logo_green.png
  uploads:
    title: Uploads
    output: true
  assets:
    title: assets
    output: true
  authors:
    title: authors
    output: true
  faq:
    title: faq
    output: true
  formats:
    title: formats
    output: true
  press:
    title: press
    output: true
  sections:
    title: sections
    output: true
  support-articles:
    title: support articles
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    format: ''
    page: ''
    image: ''
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/post/:title.html"
    asset: ''
    image: ''
    author: ''
- scope:
    path: ''
    type: press
  values:
    image: ''
    asset: ''
    author: plynty
- scope:
    path: ''
    type: faq
  values:
    author: plynty
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: https://plynty.com/uploads/plynty_logo_green.png
description: simple, convenient, personalized
email: support@plynty.com
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
assets:
  compress:
    css: true
    js: true
excerpt_separator: "<!--more-->"
gems:
- jekyll-textile-converter
- jekyll-seo-tag
